site_name: Tamar Ervin
site_description: Tamar Ervin's Personal Website
authors:
    - Tamar Ervin

# repository information
repo_url: https://github.com/tamarervin/tamarervin
edit_uri: blob/master/mysite/docs/

# copyright
copyright: Copyright &copy; 2021 Tamar Ervin

# social links
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<tamarervin@gmail.com>
    - icon: fontawesome/brands/github
      link: https://github.com/tamarervin
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tamar-ervin


# site navigation
nav:
  - Home: index.md
  - Resume: resume.md
  - Research: research.md
  - Written Work: write.md

# theme
theme:
  name: material
  language: en
  palette:
    primary: pink
    accent: deep orange
  logo: img/sun.png
  favicon: img/sun.png
  font:
    code: Oswald
  features:
    - navigation.top
    - header.autohide

# site search
plugins:
  - search:
      lang: en

